#!/bin/sh
mpd --kill
mpd
tmux neww 'ncmpcpp -s visualizer'
tmux split-window -v 'ncmpcpp'
tmux select-pane -t 0
tmux split-window -h 'ncmpcpp'
echo 'l ' | tmux load-buffer -
tmux paste-buffer -t 1.1
tmux select-pane -t 1.2
tmux neww 'exec vim'
tmux neww 'exec ipython3'
tmux neww 'exec racket'
tmux neww 'exec ghci'
tmux select-window -t 0
