" Plugin manager
Bundle 'gmarik/vundle'

" My other bundles
Bundle 'Lokaltog/vim-easymotion'
Bundle 'altercation/vim-colors-solarized'
Bundle 'chrisbra/SudoEdit.vim'
Bundle 'ervandew/supertab'
Bundle 'godlygeek/tabular'
Bundle 'jpalardy/vim-slime'
Bundle 'scrooloose/nerdtree'
Bundle 'sjl/gundo.vim'
Bundle 'tomtom/tcomment_vim'
Bundle 'tpope/vim-abolish'
Bundle 'tpope/vim-fugitive'
Bundle 'tpope/vim-pathogen'
Bundle 'tpope/vim-repeat'
Bundle 'tpope/vim-surround'
Bundle 'tpope/vim-unimpaired'
Bundle 'vim-scripts/YankRing.vim'
Bundle 'vim-scripts/bufkill.vim'
Bundle 'vim-scripts/javacomplete'
Bundle 'vim-scripts/pep8'
Bundle 'wlangstroth/vim-racket'
Bundle 'zaiste/tmux.vim'

Bundle 'git://vim-latex.git.sourceforge.net/gitroot/vim-latex/vim-latex' 
